- hosts: nautilus_app2
  gather_facts: false
  become: true

  vars:
    zip_name: /backup/xfusioncorp_media.zip
    zip_dir: /var/www/html/media
    backup_dir: /backup/

  tasks:
    - name: Create a zip archive
      archive:
        path: "{{ zip_dir }}"
        dest: "{{ zip_name }}"
        format: zip
    - name: Copy backup zip to backup server
      synchronize: "src={{ zip_name }} dest={{ backup_dir }}"
      delegate_to: nautilus_backup_server
