- hosts: stapp01
  gather_facts: false
  become: true

  vars:
    base_dir: /opt/devops

  tasks:
    - replace:
        path: "{{ base_dir }}/blog.txt"
        replace: Nautilus
        regexp: xFusionCorp
- hosts: stapp02
  gather_facts: false
  become: true

  vars:
    base_dir: /opt/devops

  tasks:
    - replace:
        path: "{{ base_dir }}/story.txt"
        replace: KodeKloud
        regexp: Nautilus
- hosts: stapp03
  gather_facts: false
  become: true

  vars:
    base_dir: /opt/devops

  tasks:
    - replace:
        path: "{{ base_dir }}/media.txt"
        replace: xFusionCorp Industries
        regexp: KodeKloud

