apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /var/log/nginx
          name: shared-logs
    - name: sidecar-container
      image: ubuntu:latest
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log/nginx
      command:
        - /bin/sh
        - -c
      args:
        - while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done
  volumes:
    - name: shared-logs
      emptyDir: {}
  restartPolicy: Always
