apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    app: httpd-pod
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 20Mi
        requests:
          cpu: 100m
          memory: 15Mi
  restartPolicy: Always
