apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order = "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
type: Opaque
data:
  root: "cm9vdA=="
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
data:
  user: "dXNlcg=="
  pass: "cGFzcw=="
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db
type: Opaque
data:
  host: "bXlzcWwtc2VydmljZQ=="
  database: "bXlzcWxfZGF0YWJhc2U="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-wp
  labels:
    app: lamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp
  template:
    metadata:
      name: lamp
      labels:
        app: lamp
    spec:
      containers:
        - name: httpd-php-container
          image: webdevops/php-apache:alpine-3-php7
          volumeMounts:
            - mountPath: /opt/docker/etc/php/php.ini
              name: php-config
              subPath: php.ini
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root
                  name: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: mysql-db
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mysql-db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mysql-user
        - name: mysql-container
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root
                  name: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database
                  name: mysql-db
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: host
                  name: mysql-db
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pass
                  name: mysql-user
      volumes:
        - name: php-config
          configMap:
            name: php-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  selector:
    app: lamp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lamp
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP